### ISSUE TITLE
A better ground API to build on

### ISSUE THREAD

**Issue by mhenrixon** [antonzaytsev/basecampx-api-ruby#2]
I just had a browse through the code while looking for a quick and dirty solution to pulling tasks, lists and calendars from Basecamp X. 

I have some strong opinions on the subject I am not going to get into any details I just have a simple suggestion. 

The gem you copied the original code from really sucks in my humble opinion. First of all there are no tests. If you truly want to build an API wrapper for basecamp x I suggest you have a look at http://peter-murach.github.com/github/ . I feel that's the way an API wrapper should be built in ruby. 

Second, I am unsure what you intend to do with the config.yaml files but I don't think anyone in their right mind will want that. Most people Heroku or VPS prefer to have environment variables or reading from something outside the repo for their client_id and client_secrets and it should be passed in to the gem. The gem shouldn't care the least of how that is stored and such it should just use whatever is provided but don't take my word for it I am just a noob check how it's done in the repo of http://peter-murach.github.com/github/ .

**Comment by mhenrixon** [comment]
I did however find one thing that truly sucked with http://peter-murach.github.com/github/  and that is thread safety. I believe that gem will run into problems during high processing.

**Comment by antonzaytsev** [comment]
Big thanks for your comments above, didn't expect someone will look in my code and may use it :)

About tests I agree with you and thank you for the link on github ruby api wrapper will check how he/they did test for api wrapper, because I don't know much about testing, especially about testing api wrapper.

Good idea to get rid of yaml config file as I thought may be better allow user create connection in initializer or use env data by default as you suggested.

Will be great if you can help me with real changes in code or if you find any other issues in my code please tell me.
